# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from payfactory_python_sdk import Payfactory

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        payfactory = Payfactory(
        
                        api_key = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(payfactory)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
