# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import payfactory_python_sdk
from payfactory_python_sdk.model.person_model import PersonModel
from payfactory_python_sdk import configuration


class TestPersonModel(unittest.TestCase):
    """PersonModel unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
