# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from payfactory_python_sdk.paths.v1_application_submit.post import CreateNewApplication
from payfactory_python_sdk.paths.v1_application_details_app_id.get import GetApplicationDetails
from payfactory_python_sdk.paths.v1_application_status_app_id.get import GetApplicationStatus
from payfactory_python_sdk.paths.v1_application_delete_app_id.delete import RemoveById
from payfactory_python_sdk.paths.v1_application_start_underwriting_app_id.post import StartUnderwritingProcess
from payfactory_python_sdk.apis.tags.application_api_raw import ApplicationApiRaw


class ApplicationApi(
    CreateNewApplication,
    GetApplicationDetails,
    GetApplicationStatus,
    RemoveById,
    StartUnderwritingProcess,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ApplicationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ApplicationApiRaw(api_client)
