# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from payfactory_python_sdk.paths.v1_reporting_ach_transactions_reference_id.get import GetAchTransactionsByReferenceIdRaw
from payfactory_python_sdk.paths.v1_reporting_deposits.get import GetDepositsRaw
from payfactory_python_sdk.paths.v1_reporting_deposits_number_of_deposits.get import GetDepositsByCountRaw
from payfactory_python_sdk.paths.v1_reporting_deposits_reference_id.get import GetDepositsByReferenceIdRaw


class ReportingApiRaw(
    GetAchTransactionsByReferenceIdRaw,
    GetDepositsRaw,
    GetDepositsByCountRaw,
    GetDepositsByReferenceIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
