# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateSessionRequestSignerModel(TypedDict):
    # Email address of the merchant signer(the user who you are redirecting to complete the application
    emailAddress: str

    # FirstName of the Signer
    firstName: str

    # LastName of the Signer
    lastName: str

class OptionalCreateSessionRequestSignerModel(TypedDict, total=False):
    pass

class CreateSessionRequestSignerModel(RequiredCreateSessionRequestSignerModel, OptionalCreateSessionRequestSignerModel):
    pass
