# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from payfactory_python_sdk.type.create_session_request_signer_model import CreateSessionRequestSignerModel
from payfactory_python_sdk.type.session_business_details_model import SessionBusinessDetailsModel

class RequiredCreateSessionRequest(TypedDict):
    signer: CreateSessionRequestSignerModel

    # Name of the merchant account
    companyName: str

    # Url to redirect the merchant user to when clicking the back button
    redirectUrl: str

    # Url to redirect the merchant user to upon completing the application
    completeUrl: str

    # Url to redirect to the merchant user to when their session is expired
    refreshUrl: str

    # Unique identifier for the merchant in your system
    externalId: str

class OptionalCreateSessionRequest(TypedDict, total=False):
    # Id of the Pricing Plan. Only used if enabled for the partner
    pricingPlanId: typing.Optional[str]

    businessDetails: SessionBusinessDetailsModel

class CreateSessionRequest(RequiredCreateSessionRequest, OptionalCreateSessionRequest):
    pass
