# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from payfactory_python_sdk.type.deposit_type import DepositType
from payfactory_python_sdk.type.transaction_model import TransactionModel

class RequiredDepositModel(TypedDict):
    pass

class OptionalDepositModel(TypedDict, total=False):
    date: datetime

    type: DepositType

    subMerchantId: typing.Optional[str]

    amount: typing.Union[int, float]

    transactions: typing.Optional[typing.List[TransactionModel]]

class DepositModel(RequiredDepositModel, OptionalDepositModel):
    pass
