# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTransactionMetadataRequest(TypedDict):
    # The transaction Id from the payment processor
    transactionId: str

    # Payfactoy's merchant Id
    merchantId: str

    # Name of the Cardholder
    cardHolderName: str

class OptionalTransactionMetadataRequest(TypedDict, total=False):
    # Any identifier you choose to send
    externalId: typing.Optional[str]

    # Any identifier you choose to send
    orderId: typing.Optional[str]

    # Required if partner is configured for the partner fee program
    partnerFee: typing.Optional[typing.Union[int, float]]

    # Number of items sold in the transaction
    itemCount: typing.Optional[int]

class TransactionMetadataRequest(RequiredTransactionMetadataRequest, OptionalTransactionMetadataRequest):
    pass
