# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SessionResponse(BaseModel):
    session_id: typing.Optional[typing.Optional[str]] = Field(None, alias='sessionId')

    app_id: typing.Optional[typing.Optional[str]] = Field(None, alias='appId')

    external_id: typing.Optional[typing.Optional[str]] = Field(None, alias='externalId')

    valid_until: typing.Optional[datetime] = Field(None, alias='validUntil')

    complete: typing.Optional[bool] = Field(None, alias='complete')

    url: typing.Optional[typing.Optional[str]] = Field(None, alias='url')

    expired: typing.Optional[bool] = Field(None, alias='expired')
    class Config:
        arbitrary_types_allowed = True
