# coding: utf-8

"""
    Payfactory Api

    Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TransactionMetadataRequest(BaseModel):
    # The transaction Id from the payment processor
    transaction_id: str = Field(alias='transactionId')

    # Payfactoy's merchant Id
    merchant_id: str = Field(alias='merchantId')

    # Name of the Cardholder
    card_holder_name: str = Field(alias='cardHolderName')

    # Any identifier you choose to send
    external_id: typing.Optional[typing.Optional[str]] = Field(None, alias='externalId')

    # Any identifier you choose to send
    order_id: typing.Optional[typing.Optional[str]] = Field(None, alias='orderId')

    # Required if partner is configured for the partner fee program
    partner_fee: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='partnerFee')

    # Number of items sold in the transaction
    item_count: typing.Optional[typing.Optional[int]] = Field(None, alias='itemCount')
    class Config:
        arbitrary_types_allowed = True
